apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wintercms-postgres-data
  namespace: wintercms
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
