apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wintercms-data
  namespace: wintercms
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: default
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 10Gi
