# this example attempts to use the INIT_WINTER option correctly
# with an automate admin password update
version: '2.2'
services:
  winter:
    image: hiltonbanes/wintercms:php7.4-apache
    ports:
      - 8888:80
    depends_on: # slows down the container start waiting on DB up
      mariadb:
        condition: service_healthy
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mariadb #DB_HOST should match the service name of the database container
      - DB_DATABASE=wintercms
      - DB_USERNAME=root
      - DB_PASSWORD=root
      # initial DB seeding through entry point
      - INIT_WINTER=true
      - CMS_ADMIN_PASSWORD=admin # probably use the docker environment system to make a secret

  mariadb:
    image: mariadb:10.4
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wintercms
