apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: wintercms-secret
  namespace: wintercms
  labels:
    app: wintercms-app
    tier: frontend
stringData:
  DB_TYPE: pgsql
  # DB_HOST should match the service name of the database container
  DB_HOST: wintercms-postgres-service
  DB_PORT: "5432"
  DB_DATABASE: wintercms
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_REDIS_HOST: wintercms-redis-service
  CMS_LINK_POLICY: secure